// Diccionari estàtic de codis IATA -> nom de ciutat, per mostrar destinacions
// llegibles ("Roma (FCO)") sense haver de descarregar tota la base de dades
// d'aeroports de Travelpayouts a cada petició. Si un codi no hi és, es
// mostra només el codi.
const CITY_NAMES: Record<string, string> = {
  BCN: 'Barcelona',
  PMI: 'Palma de Mallorca',
  IBZ: 'Eivissa',
  MAD: 'Madrid',
  VLC: 'València',
  SVQ: 'Sevilla',
  BIO: 'Bilbao',
  AGP: 'Màlaga',
  OPO: 'Oporto',
  LIS: 'Lisboa',
  FCO: 'Roma',
  MXP: 'Milà',
  VCE: 'Venècia',
  NAP: 'Nàpols',
  CTA: 'Catània',
  PSA: 'Pisa',
  BLQ: 'Bolonya',
  LHR: 'Londres',
  LGW: 'Londres',
  STN: 'Londres',
  CDG: 'París',
  ORY: 'París',
  NCE: 'Niça',
  MRS: 'Marsella',
  LYS: 'Lió',
  BER: 'Berlín',
  MUC: 'Munic',
  FRA: 'Frankfurt',
  HAM: 'Hamburg',
  AMS: 'Amsterdam',
  BRU: 'Brussel·les',
  VIE: 'Viena',
  ZRH: 'Zúric',
  GVA: 'Ginebra',
  DUB: 'Dublín',
  CPH: 'Copenhaguen',
  ARN: 'Estocolm',
  OSL: 'Oslo',
  HEL: 'Hèlsinki',
  WAW: 'Varsòvia',
  KRK: 'Cracòvia',
  PRG: 'Praga',
  BUD: 'Budapest',
  ATH: 'Atenes',
  IST: 'Istanbul',
  SAW: 'Istanbul',
  TLV: 'Tel Aviv',
  CAI: 'El Caire',
  CMN: 'Casablanca',
  RAK: 'Marràqueix',
  DXB: 'Dubai',
  JFK: 'Nova York',
  EWR: 'Nova York',
  BOS: 'Boston',
  MIA: 'Miami',
  EAS: 'Sant Sebastià',
};

export function formatAirportLabel(code: string): string {
  const city = CITY_NAMES[code];
  return city ? `${city} (${code})` : code;
}
